version: "3.7"

services:
  # Traefik 2.0 reverse proxy with sub-domain configuration

  traefik:
    container_name: traefik
    hostname: traefik
    image: traefik:v2.1
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${DOCKERDIR}/traefik:/etc/traefik
      - ${DOCKERDIR}/shared:/shared
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/shared/.htpasswd"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAINNAME}`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.service=api@internal"
      ## DNS CHALLENGE
      - "traefik.http.routers.traefik.tls.certresolver=cf-cert"
      - "traefik.http.routers.traefik.tls.domains[0].main=*.${DOMAINNAME}"
      - "traefik.http.routers.traefik.tls.domains[0].sans=${DOMAINNAME}"
      ## HTTP REDIRECT
      - "traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirect-https.entrypoints=web"
      - "traefik.http.routers.redirect-https.middlewares=secure-redirect@file"
    networks:
      - traefik_proxy

  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: wordpress:latest
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESSPW}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ${DOCKERDIR}/wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.rule=Host(`www.${DOMAINNAME}`) || Host(`${DOMAINNAME}`)"
      - "traefik.http.routers.wordpress.tls.certresolver=cf-cert"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    networks:
      - traefik_proxy

  ghost:
    container_name: ghost
    image: ghost:latest
    restart: always
    env_file:
      - ${DOCKERDIR}/ghost/ghost.env
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.rule=Host(`blog.${DOMAINNAME}`)"
      - "traefik.http.routers.ghost.tls.certresolver=cf-cert"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
    volumes:
      - ${DOCKERDIR}/ghost:/var/lib/ghost/content
    networks:
      - traefik_proxy

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: linuxserver/mariadb
    restart: always
    depends_on:
      - traefik
    volumes:
      - ${DOCKERDIR}/mariadb:/config
      - ${DOCKERDIR}/shared:/shared
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
