version: "3.7"

services:
  # Traefik 2.0 reverse proxy with sub-domain configuration

  traefik:
    container_name: traefik
    hostname: traefik
    image: traefik:v2.1
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${DOCKERDIR}/traefik:/etc/traefik
      - ${DOCKERDIR}/shared:/shared
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAINNAME}`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.service=api@internal"
      ## Secure dashboard with basic authentication
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/shared/.htpasswd"
      ## DNS CHALLENGE
      - "traefik.http.routers.traefik.tls.certresolver=cf-cert"
      - "traefik.http.routers.traefik.tls.domains[0].main=*.${DOMAINNAME}"
      - "traefik.http.routers.traefik.tls.domains[0].sans=${DOMAINNAME}"
      ## HTTP REDIRECT
      - "traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirect-https.entrypoints=web"
      - "traefik.http.routers.redirect-https.middlewares=secure-redirect@file"
    networks:
      - traefik_proxy

  # Wordpress - This acts as the TLD.

  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: wordpress:latest
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESSPW}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ${DOCKERDIR}/wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.rule=Host(`www.${DOMAINNAME}`) || Host(`${DOMAINNAME}`)"
      - "traefik.http.routers.wordpress.tls.certresolver=cf-cert"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    networks:
      - traefik_proxy

  # Ghost - This is the blog subdomain

  ghost:
    container_name: ghost
    image: ghost:latest
    restart: always
    env_file:
      - ${DOCKERDIR}/ghost/ghost.env
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.rule=Host(`blog.${DOMAINNAME}`)"
      - "traefik.http.routers.ghost.tls.certresolver=cf-cert"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
    volumes:
      - ${DOCKERDIR}/ghost:/var/lib/ghost/content
    networks:
      - traefik_proxy

  # Nextcloud - Personal cloud storage

  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAINNAME}`)"
      - "traefik.http.routers.nextcloud.tls.certresolver=cf-cert"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      ## Headers - Not sure if needed
      - "traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud.headers.framedeny=true"
      - "traefik.http.middlewares.nextcloud.headers.sslredirect=true"
      - "traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud.headers.stsSeconds=15552000"

    volumes:
      - ${DOCKERDIR}/nextcloud:/var/www/html
    networks:
      - traefik_proxy

  # Self hosted Git repository

  gitea:
    container_name: gitea
    image: kunde21/gitea-arm
    restart: always
    ports:
      - "3000:3000"
      - "2222:22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.rule=Host(`git.${DOMAINNAME}`)"
      - "traefik.http.routers.gitea.tls.certresolver=cf-cert"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    volumes:
      - ${DOCKERDIR}/gitea:/data
    networks:
      - traefik_proxy

  # Portainer - Remote access to docker containers via web UI

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: always
    depends_on:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/portainer/data:/data
      - ${DOCKERDIR}/shared:/shared
    command: -H unix:///var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAINNAME}`)"
      - "traefik.http.routers.portainer.tls.certresolver=cf-cert"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - traefik_proxy

  # PHPmyadmin - Manage the database via web UI

  phpmyadmin:
    container_name: phpmyadmin
    image: jackgruber/phpmyadmin:latest
    restart: always
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_ABSOLUTE_URL=https://db.${DOMAINNAME}/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.rule=Host(`db.${DOMAINNAME}`)"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=cf-cert"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
    networks:
      - traefik_proxy

  # MariaDB - Open sourced relational database. MySQL equivalent.

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: linuxserver/mariadb
    restart: always
    depends_on:
      - traefik
    volumes:
      - ${DOCKERDIR}/mariadb:/config
      - ${DOCKERDIR}/shared:/shared
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
