version: "3.6"
services:

    # Traefik - reverse proxy with sub-domain configuration

    traefik:
        hostname: traefik
        image: traefik:latest
        container_name: traefik
        restart: always
        domainname: ${DOMAINNAME}
        networks:
          - default
          - traefik_proxy
        ports:
          - "80:80"
          - "443:443"
        environment:
          - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
          - CF_API_KEY=${CLOUDFLARE_API_KEY}
        labels:
          - "traefik.enable=true"
          - "traefik.backend=traefik"
          - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"  
          - "traefik.port=8080"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.auth.basic.users=${HTTP_USERNAME}:${HTTP_PASSWORD}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /Users/richardsoper/docker/traefik:/etc/traefik
          - /Users/richardsoper/docker/shared:/shared

    # Portainer - WebUI for Containers

    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: always
        command: -H unix:///var/run/docker.sock
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ${USERDIR}/docker/portainer/data:/data
          - ${USERDIR}/docker/shared:/shared
        environment:
          - TZ=${TZ}
        networks:
          - traefik_proxy
        labels:
          - "traefik.enable=true"
          - "traefik.backend=portainer"
          - "traefik.frontend.rule=Host:portainer.${DOMAINNAME}"  
          - "traefik.port=9000"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"

    # Ghost - Blog platform for personal blog

    ghost:
        image: ghost:latest
        container_name: ghost
        restart: always
        depends_on:
          - mariadb
        networks:
          - traefik_proxy
        environment:
          url: https://blog.${DOMAINNAME}
          database_client: mysql
          database_connection_host: mariadb
          database_connection_user: ghost
          database_connection_password: ${GHOSTDBPW}
          database_connection_database: ghost
        labels:
          - "traefik.enable=true"
          - "traefik.backend=ghost"
          - "traefik.frontend.rule=Host:blog.${DOMAINNAME}"  
          - "traefik.port=2368"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
          - "traefik.frontend.headers.customFrameOptionsValue=ALLOW-FROM https://blog.${DOMAINNAME}"
          - "traefik.frontend.passHostHeader=true"
        volumes:
          - ${USERDIR}/docker/ghost:/var/lib/ghost/content

    # Owncloud - Personal file storage

    owncloud:
        image: owncloud:latest
        container_name: owncloud
        restart: always
        depends_on: 
          - mariadb
        networks:
          - traefik_proxy
        ports:
          - "8000:80"
        labels:
          - "traefik.enable=true"
          - "traefik.backend=ghost1"
          - "traefik.frontend.rule=Host:owncloud.${DOMAINNAME}"  
          - "traefik.port=80"
          - "traefik.docker.network=traefik_proxy"
          - "traefik.frontend.headers.SSLRedirect=true"
          - "traefik.frontend.headers.STSSeconds=315360000"
          - "traefik.frontend.headers.browserXSSFilter=true"
          - "traefik.frontend.headers.contentTypeNosniff=true"
          - "traefik.frontend.headers.forceSTSHeader=true"
          - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
          - "traefik.frontend.headers.STSIncludeSubdomains=true"
          - "traefik.frontend.headers.STSPreload=true"
          - "traefik.frontend.headers.frameDeny=true"
        volumes:
          - ${USERDIR}/docker/owncloud:/var/www/html

    # PHPmyadmin - mySQL management UI for mariadb

    phpmyadmin:
      hostname: phpmyadmin
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      restart: always
      depends_on:
        - mariadb
      networks:
        - traefik_proxy
      environment:
        - PMA_HOST=mariadb
        - PMA_USER=root
        - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - PMA_ABSOLUTE_URI=https://phpmyadmin.${DOMAINNAME}/
      labels:
        - "traefik.enable=true"
        - "traefik.backend=phpmyadmin"
        - "traefik.frontend.rule=Host:phpmyadmin.${DOMAINNAME}"
        - "traefik.port=80"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.forceSTSHeader=true"
        - "traefik.frontend.headers.SSLHost=phpmyadmin.${DOMAINNAME}"
        - "traefik.frontend.headers.SSLForceHost=true"
        - "traefik.frontend.headers.STSIncludeSubdomains=true"
        - "traefik.frontend.headers.STSPreload=true"
        - "traefik.frontend.headers.frameDeny=true"
        - "traefik.frontend.auth.basic.usersFile=/shared/.htpasswd"

    ######### DOCKER RELATED ##########

    # Watchtower - Automatic Update of Containers/Apps

    watchtower:
        container_name: watchtower
        hostname: watchtower
        restart: always
        image: v2tec/watchtower
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: --schedule "0 0 4 * * *" --cleanup

    ######### DATABASE #########

    # Maria DB - MySQL configured for ghost, and owncloud
    
    mariadb:
      hostname: mariadb
      container_name: mariadb
      image: linuxserver/mariadb
      restart: always
      networks:
        - traefik_proxy
      volumes:
        - ${USERDIR}/docker/mariadb:/config
        - ${USERDIR}/docker/shared:/shared
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${TZ}


networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge