version: "3"

services:
  traefik:
    image: traefik:v2.0
    command: --providers.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${DOCKERDIR}/traefik:/etc/traefik
      - ${DOCKERDIR}/shared:/shared
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAINNAME}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/shared/.htpasswd"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAINNAME}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - traefik_proxy

  # wordpress:
  #   hostname: wordpress
  #   image: wordpress:latest
  #   restart: always
  #   depends_on:
  #     - mariadb
  #   environment:
  #     WORDPRESS_DB_HOST: mariadb
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: ${WORDPRESSPW}
  #     WORDPRESS_DB_NAME: wordpress
  #   volumes:
  #     - ${DOCKERDIR}/wordpress:/var/www/html
  #   labels:
  #     - traefik.http.routers.wordpress.rule=Host(`${DOMAINNAME}`)
  #   networks:
  #     - traefik_proxy

  # ghost:
  #   image: ghost:latest
  #   restart: always
  #   depends_on:
  #     - mariadb
  #   labels:
  #     - traefik.http.routers.ghost.rule=Host(`blog.${DOMAINNAME}`)
  #   networks:
  #     - traefik_proxy

  # portainer:
  #   image: portainer/portainer
  #   ports:
  #     - "9000:9000"
  #   labels:
  #     - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAINNAME}`)
  #   command: -H unix:///var/run/docker.sock
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - traefik_proxy

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - mariadb
  #   environment:
  #     - PMA_HOST=mariadb
  #     - PMA_USER=root
  #     - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - PMA_ABSOLUTE_URL=http://phpmyadmin.${DOMAINNAME}/
  #   labels:
  #     - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)
  #   networks:
  #     - traefik_proxy

  # nextcloud:
  #   image: nextcloud:latest
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - "8000:80"
  #   labels:
  #     - traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAINNAME}`)
  #   volumes:
  #     - ${DOCKERDIR}/nextcloud:/var/www/html
  #   networks:
  #     - traefik_proxy

  # mariadb:
  #   hostname: mariadb
  #   image: linuxserver/mariadb
  #   restart: always
  #   volumes:
  #     - ${DOCKERDIR}/mariadb:/config
  #     - ${DOCKERDIR}/shared:/shared
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     - TZ=${TZ}
  #   networks:
  #     - traefik_proxy

networks:
  traefik_proxy:
    external: true