version: "3.7"

services:
  # Traefik 2.0 reverse proxy with sub-domain configuration

  traefik:
    hostname: traefik
    image: traefik:v2.2
    restart: always
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    ports:
      - "80:80"
      - "443:443"
      - "8008:8008"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - traefik_data:/etc/traefik
      - shared_data:/shared
    networks:
      - traefik_swarm
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAINNAME}`)"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.service=api@internal"
        ## Secure dashboard with basic authentication
        - "traefik.http.routers.traefik.middlewares=traefik-auth"
        - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/shared/.htpasswd"
        ## DNS CHALLENGE
        - "traefik.http.routers.traefik.tls.certresolver=cf-cert"
        - "traefik.http.routers.traefik.tls.domains[0].main=*.${DOMAINNAME}"
        - "traefik.http.routers.traefik.tls.domains[0].sans=${DOMAINNAME}"
        ## HTTP REDIRECT
        - "traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.redirect-https.entrypoints=web"
        - "traefik.http.routers.redirect-https.middlewares=secure-headers@file"

  # Portainer - Remote access to docker containers via web UI

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    depends_on:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command: -H unix:///var/run/docker.sock
    networks:
      - traefik_swarm
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAINNAME}`)"
        - "traefik.http.routers.portainer.tls.certresolver=cf-cert"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  traefik_swarm:
    external: true


volumes:
  traefik_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/docker/traefik"

  shared_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/docker/shared"

  portainer_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/docker/portainer/data"