version: "3.7"

secrets:
  CF_API_EMAIL:
    external: true
  CF_API_KEY:
    external: true


services:
  # Traefik 2.0 reverse proxy with sub-domain configuration

  traefik:
    hostname: traefik
    image: traefik:v2.2
    secrets:
      - "CF_API_EMAIL"
      - "CF_API_KEY"
    environment:
      - CF_API_EMAIL_FILE=/run/secrets/CF_API_EMAIL
      - CF_API_KEY_FILE=/run/secrets/CF_API_KEY
    ports:
      - "80:80"
      - "443:443"
      - "8008:8008"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - traefik_data:/etc/traefik
      - shared_data:/shared
    networks:
      - traefik_swarm
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.richardsoper.me`)"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.service=api@internal"
        ## Secure dashboard with basic authentication
        - "traefik.http.routers.traefik.middlewares=traefik-auth"
        - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/shared/.htpasswd"
        ## DNS CHALLENGE
        - "traefik.http.routers.traefik.tls.certresolver=cf-cert"
        - "traefik.http.routers.traefik.tls.domains[0].main=*.richardsoper.me"
        - "traefik.http.routers.traefik.tls.domains[0].sans=richardsoper.me"
        ## HTTP REDIRECT
        - "traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.redirect-https.entrypoints=web"
        - "traefik.http.routers.redirect-https.middlewares=secure-headers@file"

  phpmyadmin:
    image: arm64v8/phpmyadmin
    environment:
      - PMA_HOST=wiki_bookstack_db
      - PMA_ABSOLUTE_URI=https://db.richardsoper.me/
    networks:
      - traefik_swarm
      - bookstack_swarm
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
        - "traefik.http.routers.phpmyadmin.rule=Host(`db.richardsoper.me`)"
        - "traefik.http.routers.phpmyadmin.tls.certresolver=cf-cert"
        - "traefik.http.routers.phpmyadmin.middlewares=secure-headers@file"
        - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

networks:
  traefik_swarm:
    external: true
  bookstack_swarm:
    external: true


volumes:
  traefik_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/docker/richardsoper.me/traefik"

  shared_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/docker/richardsoper.me/shared"