version: "3.7"

services:

  traefik:
    image: traefik:v2.0
    command: --providers.docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # - ${DOCKERDIR}/traefik:/etc/traefik
      - ${DOCKERDIR}/shared:/shared

  wordpress:
    hostname: wordpress
    image: wordpress:latest
    restart: always
    depends_on: 
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESSPW}
      WORDPRESS_DB_NAME: wordpress
    labels:
      - traefik.http.routers.wordpress.rule=Host(`www.${DOMAINNAME}`)

  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - mariadb
    labels:
      - traefik.http.routers.ghost.rule=Host(`blog.${DOMAINNAME}`)

  portainer:
    image: portainer/portainer
    labels:
      - traefik.http.routers.portainer.rule=Host(`portainer.localhost`)
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_ABSOLUTE_URL=http://phpmyadmin.${DOMAINNAME}/
    labels:
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)

  nextcloud:
    image: nextcloud:latest
    depends_on:
      - mariadb
    ports:
      - "8000:80"
    labels:
      - traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAINNAME}`)
    volumes:
      - ${DOCKERDIR}/nextcloud:/var/www/html


  mariadb:
    hostname: mariadb
    image: linuxserver/mariadb
    restart: always
    # volumes:
    #   - ${DOCKERDIR}/mariadb:/config
    #   - ${DOCKERDIR}/shared:/shared
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}