http:
  routers:
    appwrite:
      rule: "Host(`appwrite.richardsoper.me`)"
      service: appwrite-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - securedheaders@file
        - authelia@docker

  services:
    appwrite-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.33.16:80"
