http:
  middlewares:
    secure-lan:
      chain:
        middlewares:
          - securedheaders@file
          - compression@file
          - LAN-whitelist@file

    secure-headers:
      chain:
        middlewares:
          - securedheaders@file
          - compression@file

    compression:
      compress: {}
