http:
  routers:
    ghost:
      rule: "Host(`blog.richardsoper.me`)"
      service: ghost-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - secure-headers@file

  services:
    ghost-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://10.0.20.2:1001"
