http:
  routers:
    grafana:
      rule: "Host(`grafana.richardsoper.me`)"
      service: grafana-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - secure-headers@file

  services:
    grafana-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://10.0.20.2:3030"