http:
  middlewares:
    securedheaders:
      headers:
        forceSTSHeader: true
        sslRedirect: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        customFrameOptionsValue: "SAMEORIGIN"
        contentSecurityPolicy: "default-src https:; connect-src 'self'; font-src data:; img-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline' "