http:
  middlewares:
    securedheaders:
      headers:
        forceSTSHeader: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        customFrameOptionsValue: "SAMEORIGIN"
