http:
  routers:
    jellyfin:
      rule: "Host(`watch.richardsoper.me`) || Host(`watch.rdsv.me`) || Host(`w.rdsv.me`)"
      service: jellyfin-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - securedheaders@file

  services:
    jellyfin-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://jellyfin.internal:8096"
