http:
  routers:
    proxmox:
      rule: "Host(`proxmox.lan.richardsoper.me`)"
      service: proxmox-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - securedheaders@file
        - authelia@docker
    unifi:
      rule: "Host(`unifi.lan.richardsoper.me`)"
      service: unifi-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - securedheaders@file
        - authelia@docker
    pma:
      rule: "Host(`pma.lan.richardsoper.me`)"
      service: pma-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - securedheaders@file
        - authelia@docker

  services:
    proxmox-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "https://192.168.33.17:8006"
    unifi-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "https://192.168.33.1"
    pma-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.33.133:8080"
