http:
  routers:
    pihole:
      rule: "Host(`pihole.richardsoper.me`)"
      service: pihole-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - securedheaders@file
        - traefik-auth@docker

  services:
    pihole-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://10.0.20.3:80"
