http:
  routers:
    pihole:
      rule: "Host(`pihole.richardsoper.me`)"
      service: pihole-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - admin-redirect@file
        - secure-headers@file
        - authelia@docker
    pihole-backup:
      rule: "Host(`pihole2.richardsoper.me`)"
      service: pihole-backup-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - admin-redirect@file
        - secure-headers@file
        - authelia@docker

  services:
    pihole-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://10.0.20.3:80"
    pihole-backup-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://10.0.20.22:8080"

  middlewares:
    admin-redirect:
      redirectRegex:
        regex: "^https://(pihole.|pihole2.)?richardsoper.me/$"
        replacement: "https://${1}richardsoper.me/admin/"
