http:
  routers:
    pihole-router:
      rule: "Host(`pihole.richardsoper.me`)"
      service: route-to-rPi-service
      entryPoints:
        - web
        - websecure

  services:
    pihole-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.14:80/"
