http:
  routers:
    pihole:
      rule: "Host(`pihole.lan.richardsoper.me`)"
      service: pihole-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - admin-redirect@file
        - secure-headers@file
        - authelia@docker
    pihole-backup:
      rule: "Host(`pihole2.lan.richardsoper.me`)"
      service: pihole-backup-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - admin-redirect@file
        - secure-headers@file
        - authelia@docker

  services:
    pihole-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.33.2:80"
    pihole-backup-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.33.3:80"

  middlewares:
    admin-redirect:
      redirectRegex:
        regex: "^https://(pihole.|pihole2.)?lan.richardsoper.me/$"
        replacement: "https://${1}lan.richardsoper.me/admin/"
