http:
  routers:
    pihole-router:
      rule: "Host(`pihole.richardsoper.me`)"
      service: pihole-service
      entryPoints:
        - websecure

  services:
    pihole-service:
      loadBalancer:
        servers:
          - url: "192.168.1.14:80"
