http:
  routers:
    proxmox:
      rule: "Host(`proxmox.lan.richardsoper.me`)"
      service: proxmox-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - securedheaders@file
        - authelia@docker

  services:
    proxmox-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "https://192.168.33.17:8006"
