http:
  routers:
    scrypted:
      rule: "Host(`scrypted.lan.richardsoper.me`)"
      service: scrypted-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - secure-headers@file
        - authelia@docker

  services:
    scrypted-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "https://scrypted.internal:10443"
