http:
  routers:
    homeassistant:
      rule: "Host(`home.richardsoper.me`)"
      service: homeassistant-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - secure-headers@file
        - authelia@docker
    scrypted:
      rule: "Host(`scrypted.richardsoper.me`)"
      service: scrypted-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - secure-headers@file
        - authelia@docker

  services:
    homeassistant-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://master.server:8123"
    scrypted-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "https://imac.server:10443"
