http:
  routers:
    transmission:
      rule: "Host(`transmission.richardsoper.me`)"
      service: transmission-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - securedheaders@file
        - authelia@docker

  services:
    transmission-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://transmission.internal:9091"
