http:
  routers:
    wordpress:
      rule: "Host(`www.richardsoper.me`) || Host(`richardsoper.me`)"
      service: wordpress-service
      entryPoints:
        - websecure
      tls:
        certResolver: cf-cert
      middlewares:
        - secure-headers@file

  services:
    wordpress-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://10.0.20.2:1000"