server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://master.server:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
  - job_name: traefik
    static_configs:
      - targets:
          - localhost
        labels:
          job: traefik_logs
          __path__: /mnt/swarm/traefik/shared/logs/*log
