version: "3.7"

services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=${DB_PASSWORD}
      - DB_DATABASE=bookstackapp
      - APP_URL=https://wiki.${DOMAINNAME}
    volumes:
      - ./config:/config
    ports:
      - 6875:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.entrypoints=websecure"
      - "traefik.http.routers.bookstack.rule=Host(`wiki.${DOMAINNAME}`)"
      - "traefik.http.routers.bookstack.tls.certresolver=cf-cert"
      - "traefik.http.routers.bookstack.middlewares=secure-headers@file"
      - "traefik.http.services.bookstack.loadbalancer.server.port=6875"
      # - "traefik.port=6875"
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
      - traefik_proxy
      - bookstack_net

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data:/config
    restart: unless-stopped
    networks:
      - bookstack_net

  phpmyadmin:
    container_name: bookstack_pma
    image: jackgruber/phpmyadmin:latest
    restart: always
    depends_on:
      - bookstack_db
    environment:
      - PMA_HOST=bookstack_db
      - PMA_ABSOLUTE_URL=https://bookstack_db.${DOMAINNAME}/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack_pma.entrypoints=websecure"
      - "traefik.http.routers.bookstack_pma.rule=Host(`bookstack_db.${DOMAINNAME}`)"
      - "traefik.http.routers.bookstack_pma.tls.certresolver=cf-cert"
      - "traefik.http.routers.bookstack_pma.middlewares=secure-lan@file"
      - "traefik.http.services.bookstack_pma.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
      - bookstack_net

networks:
  bookstack_net:
    external: true
  traefik_proxy:
    external: true
