version: "3.7"

services:
  bookstack:
    image: linuxserver/bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=${DB_PASSWORD}
      - DB_DATABASE=bookstackapp
      - APP_URL=https://wiki.richardsoper.me
    volumes:
      - bookstack_data:/config
    depends_on:
      - bookstack_db
    networks:
      - traefik_swarm
      - bookstack_swarm
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bookstack.entrypoints=websecure"
        - "traefik.http.routers.bookstack.rule=Host(`wiki.richardsoper.me`)"
        - "traefik.http.routers.bookstack.tls.certresolver=cf-cert"
        - "traefik.http.routers.bookstack.middlewares=secure-headers@file"
        - "traefik.http.services.bookstack.loadbalancer.server.port=80"

  bookstack_db:
    image: linuxserver/mariadb:110.4.14mariabionic-ls80
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - bookstack_db_data:/config
    restart: unless-stopped
    networks:
      - bookstack_swarm
    deploy:
      replicas: 1

networks:
  bookstack_swarm:
    external: true
  traefik_swarm:
    external: true


volumes:
  bookstack_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/docker/richardsoper.me/bookstack/config"
  
  bookstack_db_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/docker/richardsoper.me/bookstack/data"