version: "3"
services:
  loki:
    image: grafana/loki:1.5.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:1.5.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail/docker-config.yaml:/etc/promtail/docker-config.yaml
      - ../shared/traefik.log:/var/log/traefik.log
      - ../shared/traefik-access.log:/var/log/traefik-access.log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - monitoring

networks:
  monitoring:
    external: true
  traefik_proxy:
    external: true
