version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "1000:1000"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_db:/data/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=90d"
      - "--storage.tsdb.path=/data/prometheus"
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitoring

  loki:
    image: grafana/loki:1.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:1.5.0
    volumes:
      - /var/log:/var/log
      - ./promtail/docker-config.yaml:/etc/promtail/docker-config.yaml
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - monitoring

  arm_exporter:
    image: carlosedp/arm_exporter
    container_name: arm_exporter
    restart: unless-stopped
    ports:
      - "9243:9243"
    networks:
      - monitoring

  cadvisor:
    image: zcube/cadvisor
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8181:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: "1000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secure_pass
    volumes:
      - ./grafana_db:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3030:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.rule=Host(`grafana.richardsoper.me`)"
      - "traefik.http.routers.grafana.tls.certresolver=cf-cert"
      - "traefik.http.routers.grafana.middlewares=secure-headers@file"
      - "traefik.port=3030"
    networks:
      - monitoring
      - traefik_proxy

networks:
  monitoring:
    external: true
  traefik_proxy:
    external: true
