global:
  scrape_interval: 5s
  external_labels:
    monitor: "pi-monitor"

scrape_configs:
  # - job_name: "prometheus"
  #   static_configs:
  #     - targets: ["192.168.1.22:9090"] ## IP Address of the localhost
  - job_name: "node-exporter"
    static_configs:
      - targets:
          - 192.168.1.22:9100
  - job_name: cadvisor
    static_configs:
      - targets:
          - 192.168.1.22:8181
  - job_name: arm-exporter
    static_configs:
      - targets:
          - 192.168.1.22:9243
