api:
  dashboard: true

log:
  level: DEBUG
  filePath: /shared/traefik.log
  format: json

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  http:
    acme:
      email: richardwebdesigner@me.com
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 300
        resolver:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
      # httpChallenge:
      #   entryPoint: http
