api:
  dashboard: true

log:
  level: DEBUG
  filePath: /shared/traefik.log
  format: json

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  http:
    acme:
      email: richardwebdesigner@me.com
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 300
      # httpChallenge:
      #   entryPoint: http

http:
  routers:
    route-to-pi:
      rule: "Host(`pihole.richardsoper.me`)"
      service: route-to-pi-service
      priority: 1000
      entryPoints:
        - web
      
  services:
    route-to-pi-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.14:80/admin"
