# traefik.toml

[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[log]
  level = "INFO"

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"
  [entryPoints.postgres]
    address = ":5432"

[certificatesResolvers.letsencrypt.acme]
  email = "richardwebdesigner@me.com"
  storage = "/etc/traefik/acme/acme.json"
  [certificatesResolvers.letsencrypt.acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 300
    resolvers = [&lt;dns1&gt;", "&lt;dns2&gt;"]

[api]
  dashboard = true
  debug = true

[ping]

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    defaultRule = "Host(`{{ normalize .Name }}.{{ domain }}`)"
    watch = true
    exposedByDefault = false