api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/config.yml

certificatesResolvers:
  http:
    acme:
      email: richardwebdesigner@me.com
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: http
