---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Network Services:
    - Unifi Network:
        icon: unifi-controller.png
        href: https://unifi.lan.richardsoper.me/network/default/dashboard
        description: Unifi Network dashboard
    - Primary Pi-Hole:
        icon: pi-hole.png
        href: https://pihole.richardsoper.me
        description: Primary Pi-hole
        widget:
            type: pihole
            url: http://192.168.33.2
            key: {{HOMEPAGE_FILE_PIHOLE_1}}
    - Secondary Pi-Hole:
        icon: pi-hole.png
        href: https://pihole2.richardsoper.me
        description: Secondary Pi-hole
        widget:
            type: pihole
            url: http://192.168.33.3
            key: {{HOMEPAGE_FILE_PIHOLE_2}}
- Media Services:
    - Jellyfin:
        icon: jellyfin.png
        href: https://w.rdsv.me
        description: Jellyfin streaming server
        widget:
            type: jellyfin
            url: https://w.rdsv.me
            key: {{HOMEPAGE_FILE_JELLYFIN}}
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
    - Jellyseerr:
        icon: jellyseerr.png
        href: https://request.rdsv.me
        description: Jellyfin request server
        widget:
            type: jellyseerr
            url: https://request.rdsv.me
            key: {{HOMEPAGE_FILE_JELLYSEERR}}
    - Transmission:
        icon: transmission.png
        href: https://transmission.richardsoper.me
        description: Torrent interface
        widget:
            type: transmission
            url: http://transmission.internal:9091
            username: richardsoper
            password: {{HOMEPAGE_FILE_TRANSMISSION}}
            rpcUrl: /transmission/ # Optional. Matches the value of "rpc-url" in your Transmission's settings.json file
    - Radarr:
        icon: radarr.png
        href: https://movies.richardsoper.me
        description: Movie management service
        widget:
            type: radarr
            url: http://192.168.33.200:7878
            key: {{HOMEPAGE_FILE_RADARR}}
    - Sonarr:
        icon: sonarr.png
        href: https://tv.richardsoper.me
        description: TV management service
        widget:
            type: sonarr
            url: http://192.168.33.200:8989
            key: {{HOMEPAGE_FILE_SONARR}}

- Admin Services:
    - Proxmox:
        icon: proxmox.png
        href: https://proxmox.lan.richardsoper.me
        description: Proxmox dashboard
    - Synology:
        icon: synology.png
        href: http://storage.local:5000
        description: Synology DSM dashboard
    - Portainer:
        icon: portainer.png
        href: https://portainer.richardsoper.me
        description: Portainer dashboard
    - Grafana:
        icon: grafana.png
        href: https://grafana.richardsoper.me
        description: Grafana dashboard
    - Traefik:
        icon: traefik.png
        href: https://traefik.richardsoper.me
        description: Traefik dashboard

- Everything Else:
    - Nextcloud:
        icon: nextcloud.png
        href: https://cloud.richardsoper.me
        widget:
            type: nextcloud
            url: https://cloud.richardsoper.me
            username: richardsoper
            password: {{HOMEPAGE_FILE_NEXTCLOUD}}
    - Gitlab:
        icon: gitlab.png
        href: https://gitlab.richardsoper.me
    - Gatus:
        icon: gatus.png
        href: https://gatus.richardsoper.me
        widget:
            type: gatus
            url: https://gatus.richardsoper.me