version: "3.7"

networks:
  traefik_swarm:
    external: true

volumes:
  authelia_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/authelia"

services:
  authelia:
    image: authelia/authelia
    volumes:
      - authelia_data:/config
    networks:
      - traefik_swarm
    environment:
      - TZ=America/Los_Angeles
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.authelia.entrypoints=websecure"
        - "traefik.http.routers.authelia.rule=Host(`auth.richardsoper.me`)"
        - "traefik.http.routers.authelia.tls.certresolver=cf-cert"
        - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.richardsoper.me"
        - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
        - "traefik.http.services.authelia.loadbalancer.server.port=9091"
