version: "3.7"

networks:
  traefik_swarm:
    external: true

secrets:
  AUTHELIA_JWT:
    external: true
  AUTHELIA_SESSION:
    external: true
  AUTHELIA_SMTP:
    external: true

volumes:
  authelia_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.30,nolock,soft,rw
      device: ":/volume1/swarm/authelia"

services:
  authelia:
    image: authelia/authelia:4.30.4
    volumes:
      - authelia_data:/config
    secrets:
      - AUTHELIA_JWT
      - AUTHELIA_SESSION
      - AUTHELIA_SMTP
    networks:
      - traefik_swarm
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    environment:
      - TZ=America/Los_Angeles
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/AUTHELIA_JWT
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/AUTHELIA_SESSION
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/AUTHELIA_SMTP
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.authelia.entrypoints=websecure"
        - "traefik.http.routers.authelia.rule=Host(`auth.richardsoper.me`)"
        - "traefik.http.routers.authelia.tls.certresolver=cf-cert"
        - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.richardsoper.me"
        - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
        - "traefik.http.services.authelia.loadbalancer.server.port=9091"
