version: "3.7"

networks:
  traefik_swarm:
    external: true

volumes:
  code_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/code/config"
  project_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/code/projects"

services:
  code-server:
    image: codercom/code-server:latest
    volumes:
      - code_data:/home/coder/.config
      - project_data:/home/coder/project
    networks:
      - traefik_swarm
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    environment:
      - DOCKER_USER=$USER
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.code-server.entrypoints=websecure"
        - "traefik.http.routers.code-server.rule=Host(`code.richardsoper.me`)"
        - "traefik.http.routers.code-server.tls.certresolver=cf-cert"
        - "traefik.http.routers.code-server.middlewares=secure-headers@file"
        - "traefik.http.services.code-server.loadbalancer.server.port=8080"
