version: "3.7"

secrets:
  CF_API_DDNS:
    external: true

services:
  RS:
    image: oznu/cloudflare-ddns:latest
    secrets:
      - CF_API_DDNS
    logging:
      driver: loki:latest
      options:
        loki-url: "http://master.server:3100/loki/api/v1/push"
    environment:
      - TZ=America/Los_Angeles
      - API_KEY_FILE=/run/secrets/CF_API_DDNS
      - ZONE=richardsoper.me
      - PROXIED=true
      - DNS_SERVER=10.0.20.3
    deploy:
      mode: replicated
      replicas: 1
