version: "3.7"

secrets:
  CF_API_DDNS:
    external: true

services:
  ALL_DOMAINS:
    image: favonia/cloudflare-ddns:latest
    secrets:
      - CF_API_DDNS
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    environment:
      - TZ=America/Los_Angeles
      - CF_API_TOKEN_FILE=/run/secrets/CF_API_DDNS
      - DOMAINS=richardsoper.me,peregrinesparlor.com,onefccalendar.com,rdsv.me
      - PROXIED=true
      - IP6_PROVIDER=none
    deploy:
      mode: replicated
      replicas: 1
