version: "3.7"

volumes:
  discord_bot_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/discord/config"

services:
  discord_role_bot:
    image: richardsoper/discord-role-bot:latest
    environment:
      - DISCORD_TOKEN=asd123
      - CHANNEL_ID=123
    volumes:
      - discord_bot_data:/app/config
    logging:
      driver: loki
      options:
        loki-url: "http://master.server:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
