version: "3.7"

secrets:
  GHOST_DB:
    external: true
  TZ:
    external: true

networks:
  traefik_swarm:
    external: true

volumes:
  ghost_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/ghost"

services:
  ghost:
    image: ghost:4.20.4-alpine
    volumes:
      - ghost_data:/var/lib/ghost/content
    networks:
      - traefik_swarm
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    environment:
      database__client: mysql
      database__connection__host: 192.168.33.32
      database__connection__port: 3307
      database__connection__user: ghost
      database__connection__password: SUPER_SECRET_PASSWORD
      database__connection__database: ghost
      url: https://blog.richardsoper.me
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ghost.entrypoints=websecure"
        - "traefik.http.routers.ghost.rule=Host(`blog.richardsoper.me`)"
        - "traefik.http.routers.ghost.tls.certresolver=cf-cert"
        - "traefik.http.routers.ghost.middlewares=secure-headers@file"
        - "traefik.http.services.ghost.loadbalancer.server.port=2368"
