version: "3.7"

secrets:
  GHOST_DB:
    external: true
  TZ:
    external: true

networks:
  traefik_swarm:
    external: true

volumes:
  ghost_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/ghost"

services:
  ghost:
    image: ghost:3-alpine
    volumes:
      - ghost_data:/var/lib/ghost
    networks:
      - traefik_swarm
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ghost.entrypoints=websecure"
        - "traefik.http.routers.ghost.rule=Host(`blog.richardsoper.me`)"
        - "traefik.http.routers.ghost.tls.certresolver=cf-cert"
        - "traefik.http.routers.ghost.middlewares=secure-headers@file"
        - "traefik.http.services.ghost.loadbalancer.server.port=2368"