version: "3.7"

networks:
  traefik_swarm:
    external: true

secrets:
  HOMEPAGE_FILE_PIHOLE_1:
    external: true
  HOMEPAGE_FILE_PIHOLE_2:
    external: true
  HOMEPAGE_FILE_JELLYFIN:
    external: true
  HOMEPAGE_FILE_JELLYSEERR:
    external: true
  HOMEPAGE_FILE_RADARR:
    external: true
  HOMEPAGE_FILE_SONARR:
    external: true
  HOMEPAGE_FILE_NEXTCLOUD:
    external: true
  HOMEPAGE_FILE_TRANSMISSION:
    external: true

volumes:
  homepage_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/homepage"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - homepage_data:/app/config
    secrets:
      - HOMEPAGE_FILE_PIHOLE_1
      - HOMEPAGE_FILE_PIHOLE_2
      - HOMEPAGE_FILE_JELLYFIN
      - HOMEPAGE_FILE_JELLYSEERR
      - HOMEPAGE_FILE_RADARR
      - HOMEPAGE_FILE_SONARR
      - HOMEPAGE_FILE_NEXTCLOUD
      - HOMEPAGE_FILE_TRANSMISSION
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    environment:
      - UID=1028
      - GID=1028
      - HOMEPAGE_FILE_PIHOLE_1=/run/secrets/HOMEPAGE_FILE_PIHOLE_1
      - HOMEPAGE_FILE_PIHOLE_2=/run/secrets/HOMEPAGE_FILE_PIHOLE_2
      - HOMEPAGE_FILE_JELLYFIN=/run/secrets/HOMEPAGE_FILE_JELLYFIN
      - HOMEPAGE_FILE_JELLYSEERR=/run/secrets/HOMEPAGE_FILE_JELLYSEERR
      - HOMEPAGE_FILE_RADARR=/run/secrets/HOMEPAGE_FILE_RADARR
      - HOMEPAGE_FILE_SONARR=/run/secrets/HOMEPAGE_FILE_SONARR
      - HOMEPAGE_FILE_NEXTCLOUD=/run/secrets/HOMEPAGE_FILE_NEXTCLOUD
      - HOMEPAGE_FILE_TRANSMISSION=/run/secrets/HOMEPAGE_FILE_TRANSMISSION
    networks:
      - traefik_swarm
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.homepage.entrypoints=websecure"
        - "traefik.http.routers.homepage.rule=Host(`homepage.richardsoper.me`)"
        - "traefik.http.routers.homepage.tls.certresolver=cf-cert"
        - "traefik.http.routers.homepage.middlewares=secure-headers@file,authelia@docker"
        - "traefik.http.services.homepage.loadbalancer.server.port=3000"
