version: "3.7"

networks:
  traefik_swarm:
    external: true

volumes:
  kuma_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/uptime"

services:
  kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - kuma_data:/app/data
    networks:
      - traefik_swarm
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
        - "traefik.http.routers.uptime-kuma.rule=Host(`uptime.richardsoper.me`)"
        - "traefik.http.routers.uptime-kuma.tls.certresolver=cf-cert"
        - "traefik.http.routers.uptime-kuma.middlewares=secure-headers@file"
        - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
