version: "3.7"

networks:
  traefik_swarm:
    external: true

volumes:
  gitea_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/gitea"

services:
  speedtest:
    image: adolfintel/speedtest
    environment:
      - MODE=standalone
      - TELEMETRY=true
      - ENABLE_ID_OBFUSCATION=true
      - PASSWORD="yourPasswordHere"
    networks:
      - traefik_swarm
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.librespeed.entrypoints=websecure"
        - "traefik.http.routers.librespeed.rule=Host(`speedtest.richardsoper.me`)"
        - "traefik.http.routers.librespeed.tls.certresolver=cf-cert"
        - "traefik.http.routers.librespeed.middlewares=secure-headers@file"
        - "traefik.http.services.librespeed.loadbalancer.server.port=80"