version: "3.0"

networks:
  traefik_swarm:
    external: true

services:
  littlelink-server:
    image: ghcr.io/techno-tim/littlelink-server:latest
    environment:
      - AVATAR_2X_URL=https://gitlab.richardsoper.me/uploads/-/system/user/avatar/2/avatar.png?width=400
      - AVATAR_ALT=Richard Soper Profile Pic
      - AVATAR_URL=https://gitlab.richardsoper.me/uploads/-/system/user/avatar/2/avatar.png?width=200
      - BIO=QA Automation Engineer | Cardboard Collector | Homelab
      - BUTTON_ORDER=MASTODON,LINKED_IN,MMA CALENDARS
      - CUSTOM_BUTTON_ALT_TEXT=Some of the projects I am currently working on,A subscribable calendar for MMA
      - CUSTOM_BUTTON_COLOR=#000000,#000000
      - CUSTOM_BUTTON_ICON=fas fa-cog,fas fa-hand-fist
      - CUSTOM_BUTTON_NAME=PERSONAL PROJECTS,MMA CALENDARS
      - CUSTOM_BUTTON_TEXT=Personal Projects,MMA Calendars
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff,#ffffff
      - CUSTOM_BUTTON_URL=https://blog.richardsoper.me/projects/,https://mmacalendars.com
      - FAVICON_URL=https://gitlab.richardsoper.me/uploads/-/system/user/avatar/2/avatar.png?width=200
      - FOOTER=Richard Soper © 2024
      - GHOST=https://blog.richardsoper.me
      - GITHUB=https://github.com/rsoper
      - GITLAB=https://gitlab.richardsoper.me/richardsoper
      - LANG=en
      - LINKED_IN=https://www.linkedin.com/in/richardsoper
      - MASTODON=https://fosstodon.org/@richards
      - MATRIX=https://matrix.to/#/@richard:matrix.richardsoper.me
      - META_AUTHOR=Richard Soper
      - META_DESCRIPTION=QA Automation Engineer | Cardboard Collector | Homelab
      - META_INDEX_STATUS=all
      - META_KEYWORDS=HomeLab, Engineering, MTG,
      - META_TITLE=Richard Soper
      - NAME=Richard Soper
      - OG_DESCRIPTION=The home of Richard Soper
      - OG_IMAGE=https://gitlab.richardsoper.me/uploads/-/system/user/avatar/2/avatar.png?width=400
      - OG_IMAGE_HEIGHT=400
      - OG_IMAGE_WIDTH=400
      - OG_SITE_NAME=Richard Soper
      - OG_TITLE=Richard Soper
      - OG_URL=https://richardsoper.me
      - THEME=Dark
    networks:
      - traefik_swarm
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.littlelink.entrypoints=websecure"
        - "traefik.http.routers.littlelink.rule=Host(`richardsoper.me`) || Host(`www.richardsoper.me`)"
        - "traefik.http.routers.littlelink.tls.certresolver=cf-cert"
        - "traefik.http.routers.littlelink.middlewares=secure-headers@file"
        - "traefik.http.services.littlelink.loadbalancer.server.port=3000"
