version: "3.2"

networks:
  traefik_swarm:
    external: true
  service_network:
    driver: overlay
    attachable: true

volumes:
  jellyseerr_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/jellyseerr"
  radarr_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/radarr"
  jackett_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/jackett"
  sonarr_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/sonarr"
  media_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/media_data"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1028
      - PGID=1028
      - TZ=America/Los_Angeles
    volumes:
      - radarr_data:/config
      - media_data:/data
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - traefik_swarm
      - service_network
    ports:
      - 7878:7878
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.radarr.entrypoints=websecure"
        - "traefik.http.routers.radarr.rule=Host(`movies.richardsoper.me`)"
        - "traefik.http.routers.radarr.tls.certresolver=cf-cert"
        - "traefik.http.routers.radarr.middlewares=secure-headers@file,authelia@docker"
        - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    environment:
      - PUID=1028
      - PGID=1028
      - TZ=America/Los_Angeles
    volumes:
      - jackett_data:/config
      - media_data:/data
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - traefik_swarm
      - service_network
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jackett.entrypoints=websecure"
        - "traefik.http.routers.jackett.rule=Host(`jackett.richardsoper.me`)"
        - "traefik.http.routers.jackett.tls.certresolver=cf-cert"
        - "traefik.http.routers.jackett.middlewares=secure-headers@file,authelia@docker"
        - "traefik.http.services.jackett.loadbalancer.server.port=9117"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1028
      - PGID=1028
      - TZ=America/Los_Angeles
    volumes:
      - sonarr_data:/config
      - media_data:/data
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - traefik_swarm
      - service_network
    ports:
      - 8989:8989
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sonarr.entrypoints=websecure"
        - "traefik.http.routers.sonarr.rule=Host(`tv.richardsoper.me`)"
        - "traefik.http.routers.sonarr.tls.certresolver=cf-cert"
        - "traefik.http.routers.sonarr.middlewares=secure-headers@file,authelia@docker"
        - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  solverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
    networks:
      - service_network
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
    ports:
      - 5055:5055
    volumes:
      - jellyseerr_config:/app/config
    networks:
      - traefik_swarm
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyseerr.entrypoints=websecure"
        - "traefik.http.routers.jellyseerr.rule=Host(`request.richardsoper.me`) || Host(`request.rdsv.me`)"
        - "traefik.http.routers.jellyseerr.tls.certresolver=cf-cert"
        - "traefik.http.routers.jellyseerr.middlewares=secure-headers@file"
        - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
