version: "3.2"

networks:
  traefik_swarm:
    external: true
  media_net:
    driver: overlay
    attachable: true

secrets:
  TZ:
    external: true
  TM_USER:
    external: true
  TM_PASS:
    external: true

volumes:
  jellyfin_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/jellyfin/config"
  jellyfin_media:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/media_data"
  jellyfin_cache:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/jellyfin/cache"

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    environment:
      - PUID=1028
      - PGID=1028
      - JELLYFIN_PublishedServerUrl=https://watch.richardsoper.me
    volumes:
      - jellyfin_config:/config
      - jellyfin_media:/media
      - jellyfin_cache:/cache
    networks:
      - traefik_swarm
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyfin.entrypoints=websecure"
        - "traefik.http.routers.jellyfin.rule=Host(`watch.richardsoper.me`)"
        - "traefik.http.routers.jellyfin.tls.certresolver=cf-cert"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"