version: "3.2"

networks:
  monitoring_agents:
    external: true

volumes:
  promtail_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/monitoring/promtail"
  loki_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/monitoring/loki"

services:
  loki:
    image: grafana/loki:1.5.0
    volumes:
      - loki_config:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring_agents
    logging:
      driver: loki:latest
      options:
        loki-url: "http://master.server:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]

  promtail:
    image: grafana/promtail:1.5.0
    volumes:
      - /var/log:/var/log
      - promtail_config:/etc/promtail/
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - monitoring_agents
    logging:
      driver: loki:latest
      options:
        loki-url: "http://master.server:3100/loki/api/v1/push"
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
  
  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    environment:
      - PIHOLE_HOSTNAME=10.0.20.3
      - PIHOLE_PASSWORD=SUPER_SECRET_PASSWORD/API_KEY
      - INTERVAL=30s
      - PORT=9617
    networks:
      - monitoring_agents
    logging:
      driver: loki:latest
      options:
        loki-url: "http://master.server:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
  pihole-exporter2:
    image: ekofr/pihole-exporter:latest
    environment:
      - PIHOLE_HOSTNAME=10.0.20.22
      - PIHOLE_PASSWORD=SUPER_SECRET_PASSWORD/API_KEY
      - PIHOLE_PORT=8080
      - INTERVAL=30s
      - PORT=9617
    networks:
      - monitoring_agents
    logging:
      driver: loki:latest
      options:
        loki-url: "http://master.server:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
