version: '3.2'

networks:
  monitoring_agents:
    external: true
  traefik_swarm:
    external: true

services:
  cadvisor:
    image: zcube/cadvisor
    ports:
      - "8181:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring_agents
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  arm_exporter:
    image: carlosedp/arm_exporter
    ports:
      - "9243:9243"
    networks:
      - monitoring_agents
    deploy:
      mode: global
      placement:
        constraints: [node.platform.arch == aarch64]
  
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /sys:/host/sys:ro
      - /etc/hostname:/etc/nodename
      - /:/rootfs:ro
      - /proc:/host/proc:ro
    networks:
      - monitoring_agents
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]