version: '3.2'

networks:
  monitoring_agents:
    external: true

volumes:
  promtail_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/monitoring/promtail"

services:
  cadvisor:
    image: zcube/cadvisor
    ports:
      - "8181:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring_agents
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
  
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /sys:/host/sys:ro
      - /etc/hostname:/etc/nodename
      - /:/rootfs:ro
      - /proc:/host/proc:ro
    networks:
      - monitoring_agents
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  loki:
    image: grafana/loki:1.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring_agents
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]

  promtail:
    image: grafana/promtail:1.5.0
    volumes:
      - /var/log:/var/log
      - promtail_config:/etc/promtail/
      ## Need to adjust the traefik log config to avoid accidentally sharing the .htpasswd file like a moron. 
      # - ../shared/traefik.log:/var/log/traefik.log
      # - ../shared/traefik-access.log:/var/log/traefik-access.log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - monitoring_agents
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]