version: "3.2"

networks:
  monitoring_agents:
    external: true
  traefik_swarm:
    external: true

volumes:
  promtail_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/monitoring/promtail"
  loki_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/monitoring/loki"
  prometheus_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/monitoring/prometheus_db"
  prometheus_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/monitoring/prometheus"
  grafana_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/monitoring/grafana_db"

secrets:
  GF_ADMIN_PASSWORD:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.41.0
    user: "1028"
    volumes:
      - prometheus_config:/etc/prometheus
      - prometheus_data:/data/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.size=3GB"
      - "--storage.tsdb.path=/data/prometheus"
    ports:
      - "9090:9090"
    networks:
      - monitoring_agents
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]

  grafana:
    image: grafana/grafana:9.3.2
    user: "1028"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/GF_ADMIN_PASSWORD
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    secrets:
      - "GF_ADMIN_PASSWORD"
    networks:
      - monitoring_agents
      - traefik_swarm
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.rule=Host(`grafana.richardsoper.me`)"
        - "traefik.http.routers.grafana.tls.certresolver=cf-cert"
        - "traefik.http.routers.grafana.middlewares=secure-headers@file"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  loki:
    image: grafana/loki:1.5.0
    volumes:
      - loki_config:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring_agents
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.platform.os == linux]

  promtail:
    image: grafana/promtail:1.5.0
    volumes:
      - /var/log:/var/log
      - promtail_config:/etc/promtail/
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - monitoring_agents
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
