version: '3.2'

networks:
  cloud_net:
    external: true
  traefik_swarm:
    external: true

volumes:
  application:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/docker/richardsoper.me/nextcloud/application"

  database:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/docker/richardsoper.me/nextcloud/data"

secrets:
  cloud_db_pass:
    external: true
  TZ:
    external: true
  MYSQL_ROOT:
    external: true

services:
  nextcloud:
    image: nextcloud:latest
    user: "33"
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_PASSWORD_FILE=/run/secrets/cloud_db_pass
    ports:
      - "8000:80"
    volumes:
      - application:/var/www/html
    secrets:
      - "cloud_db_pass"
    networks:
      - traefik_swarm
      - cloud_net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nextcloud.entrypoints=websecure"
        - "traefik.http.routers.nextcloud.rule=Host(`cloud.richardsoper.me`)"
        - "traefik.http.routers.nextcloud.tls.certresolver=cf-cert"
        - "traefik.http.routers.nextcloud.middlewares=secure-headers@file"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      

  mariadb:
    image: linuxserver/mariadb:110.4.14mariabionic-ls80
    user: "33"
    volumes:
      - database:/config
    secrets:
      - "cloud_db_pass"
      - "TZ"
      - "MYSQL_ROOT"
    environment:
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/MYSQL_ROOT
      - FILE__TZ=/run/secrets/TZ
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud
      - FILE__MYSQL_PASSWORD=/run/secrets/cloud_db_pass
    networks:
      - cloud_net
    deploy:
      mode: replicated
      replicas: 1