version: '3.2'

networks:
  cloud_net:
    external: true
  traefik_swarm:
    external: true

secrets:
  cloud_db_pass:
    external: true
  MYSQL_ROOT:
    external: true

volumes:
  application:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/docker/richardsoper.me/nextcloud/application"


services:
  nextcloud:
    image: nextcloud:latest
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_PASSWORD_FILE=/run/secrets/cloud_db_pass
    ports:
      - "8000:80"
    volumes:
      - application:/var/www/html
    secrets:
      - "cloud_db_pass"
    networks:
      - traefik_swarm
      - cloud_net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nextcloud.entrypoints=websecure"
        - "traefik.http.routers.nextcloud.rule=Host(`cloud.richardsoper.me`)"
        - "traefik.http.routers.nextcloud.tls.certresolver=cf-cert"
        - "traefik.http.routers.nextcloud.middlewares=nextcloud-headers@file"
        - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      

  mariadb:
    image: mariadb
    volumes:
      - /mnt/docker/richardsoper.me/nextcloud/data:/config
    secrets:
      - "cloud_db_pass"
      - "MYSQL_ROOT"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT
      MYSQL_USER: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_PASSWORD_FILE: /run/secrets/cloud_db_pass
    networks:
      - cloud_net
    deploy:
      mode: replicated
      replicas: 1