version: "3.7"

services:
  OFC_Cal:
    image: registry.richardsoper.me/richardsoper/onechampcalendar:latest
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    networks:
      - traefik_swarm
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.onefc-calendar.entrypoints=websecure"
        - "traefik.http.routers.onefc-calendar.rule=Host(`onefccalendar.com`)"
        - "traefik.http.routers.onefc-calendar.tls.certresolver=cf-cert"
        - "traefik.http.routers.onefc-calendar.middlewares=secure-headers@file"
        - "traefik.http.services.onefc-calendar.loadbalancer.server.port=3001"