version: "3.7"

services:
  OFC_Cal:
    image: registry.richardsoper.me/richardsoper/onechampcalendar:latest
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
