version: "3.7"

volumes:
  reddit_scrape_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.30,nolock,soft,rw
      device: ":/volume1/swarm/reddit_scrape"

services:
  reddit_scrape:
    image: registry.richardsoper.me/richardsoper/reddit-scrape
    volumes:
      - reddit_scrape_data:/app/config
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: replicated
      replicas: 1
