version: "3.7"

networks:
  traefik_swarm:
    external: true

volumes:
  synapse_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.32,nolock,soft,rw
      device: ":/volume1/swarm/synapse"

services:
  synapse:
    image: matrixdotorg/synapse:latest
    volumes:
      - synapse_data:/data
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    networks:
      - traefik_swarm
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.synapse.entrypoints=websecure"
        - "traefik.http.routers.synapse.rule=Host(`matrix.richardsoper.me`)"
        - "traefik.http.routers.synapse.tls.certresolver=cf-cert"
        - "traefik.http.routers.synapse.middlewares=secure-headers@file"
        - "traefik.http.services.synapse.loadbalancer.server.port=8008"
