version: "3.7"

secrets:
  CF_API_EMAIL:
    external: true
  CF_API_KEY:
    external: true

networks:
  traefik_swarm:
    external: true

volumes:
  traefik_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.31,nolock,soft,rw
      device: ":/volume1/swarm/traefik"

  shared_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=192.168.33.31,nolock,soft,rw
      device: ":/volume1/swarm/shared"

services:
  traefik:
    hostname: traefik
    image: traefik:v2.5
    secrets:
      - "CF_API_EMAIL"
      - "CF_API_KEY"
    environment:
      - CF_API_EMAIL_FILE=/run/secrets/CF_API_EMAIL
      - CF_API_KEY_FILE=/run/secrets/CF_API_KEY
    ports:
      - "80:80"
      - "443:443"
      - "8008:8008"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - traefik_data:/etc/traefik
      - shared_data:/shared
    networks:
      - traefik_swarm
    logging:
      driver: loki:latest
      options:
        loki-url: "http://logging.richardsoper.me:3100/loki/api/v1/push"
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.richardsoper.me`)"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.service=api@internal"
        ## Secure dashboard with basic authentication
        - "traefik.http.routers.traefik.middlewares=authelia@docker"
        ## DNS CHALLENGE
        - "traefik.http.routers.traefik.tls.certresolver=cf-cert"
        - "traefik.http.routers.traefik.tls.domains[0].main=*.richardsoper.me"
        - "traefik.http.routers.traefik.tls.domains[0].sans=richardsoper.me"
        ## HTTP REDIRECT
        - "traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.redirect-https.entrypoints=web"
        - "traefik.http.routers.redirect-https.middlewares=secure-headers@file"
