version: "3.7"

secrets:
  wordpress_db_password:
    external: true
  TZ:
    external: true

networks:
  traefik_swarm:
    external: true

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.0.20.30,nolock,soft,rw
      device: ":/volume1/swarm/wordpress/app"

services:
  wordpress:
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - traefik_swarm
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wordpress.entrypoints=websecure"
        - "traefik.http.routers.wordpress.rule=Host(`www.richardsoper.me`) || Host(`richardsoper.me`)"
        - "traefik.http.routers.wordpress.tls.certresolver=cf-cert"
        - "traefik.http.routers.wordpress.middlewares=secure-headers@file"
        - "traefik.http.services.wordpress.loadbalancer.server.port=80"