global:
  scrape_interval: 5s
  external_labels:
    monitor: "pi-monitor"

scrape_configs:
  # - job_name: "prometheus"
  #   static_configs:
  #     - targets: ["10.0.20.2:9090"] ## IP Address of the localhost
  - job_name: "node-exporter"
    dns_sd_configs:
      - names:
        - 'tasks.node-exporter'
        type: 'A'
        port: 9100
  - job_name: cadvisor
    dns_sd_configs:
      - names:
        - 'tasks.cadvisor'
        type: 'A'
        port: 8080
  - job_name: arm_exporter
    dns_sd_configs:
      - names:
        - 'tasks.arm_exporter'
        type: 'A'
        port: 9243
  - job_name: traefik
    static_configs:
      - targets:
          - master.server:8008
