version: "3.7"

services:
  ssh-log-to-influx:
    image: acouvreur/ssh-log-to-influx
    container_name: ssh-log-to-influx
    build: ./
    restart: always
    environment:
      - INFLUX_URL=influxdb
      - INFLUX_DB=telegraf
    ports:
      - 7070:7070/tcp
    networks:
      - monitoring

  #----------------------------------------------#
  # InfluxDB : time series database
  #----------------------------------------------#
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      - monitoring

networks:
  monitoring:
    external: true
